spring:
  application.name: gateway-service-api
  zipkin.enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-ignore: ignore-unknown
    deserialization:
      fail-on-unknown-properties: false

com.marketplace:
  gateway:
    port: 8080
    auth:
      marketplace-name: ${PROJECT_NAME}
      marketplace-pass: ${PROJECT_PASS}

# jwt token
jwt:
  secret: ${SECRET}
  issuer: https://authorization-server.com
  token-expires-at: 480_000

# services
service-road-map:
  service: (?<service>.*?)
  auth-not-required-url-list:
    - ^${service-road-map.service}/auth/update-profile/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/confirm$
    - ^${service-road-map.service}/api-docs/*
  blackListWords:
    - internal
    - admin
    - actuator
  services:
    -   # authentication services
      alias: auth
      name: auth-service-api
      port: 8080
      authRequired: false
    -   # profile services
      alias: profile
      name: profile-service-api
      port: 8080
      authRequired: true
